//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golden_hand.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documet
    {
        public int DocumentID { get; set; }
        public string Name_Document { get; set; }
        public int ClientID { get; set; }
        public int JewelID { get; set; }
        public int UserID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Jewel Jewel { get; set; }
        public virtual User User { get; set; }
    }
}
