//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golden_hand.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jewel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jewel()
        {
            this.Documet = new HashSet<Documet>();
        }
    
        public int JewelID { get; set; }
        public string Name_jewel { get; set; }
        public string Description { get; set; }
        public decimal Cost { get; set; }
        public System.DateTime Stored_by { get; set; }
        public bool Payment_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documet> Documet { get; set; }
    }
}
